'use client';

import React from 'react';
import * as Lucide from 'lucide-react';
import type { LucideIcon, LucideProps } from 'lucide-react';
import { AnimatedIcon, type AnimationPreset } from './AnimatedIcon';

type WrappedIconProps = LucideProps & { preset?: AnimationPreset };

function wrap(icon: LucideIcon, defaultPreset: AnimationPreset) {
  const Wrapped = React.forwardRef<SVGSVGElement, WrappedIconProps>(({ preset, ...props }, ref) => (
    <AnimatedIcon icon={icon} preset={preset ?? defaultPreset} {...props} />
  ));
  Wrapped.displayName = `Animated(${icon.displayName || 'Icon'})`;
  return Wrapped;
}

export const Activity = wrap(Lucide.Activity, 'draw');
export const AlertCircle = wrap(Lucide.AlertCircle, 'shake');
export const AlertTriangle = wrap(Lucide.AlertTriangle, 'shake');
export const ArrowDownToLine = wrap(Lucide.ArrowDownToLine, 'slide-down');
export const ArrowLeft = wrap(Lucide.ArrowLeft, 'slide-left');
export const ArrowRight = wrap(Lucide.ArrowRight, 'slide-right');
export const Ban = wrap(Lucide.Ban, 'shake');
export const Bookmark = wrap(Lucide.Bookmark, 'tap-fold');
export const Calendar = wrap(Lucide.Calendar, 'pop-clean');
export const CalendarDays = wrap(Lucide.CalendarDays, 'pop-clean');
export const Check = wrap(Lucide.Check, 'draw');
export const CheckCircle2 = wrap(Lucide.CheckCircle2, 'draw');
export const ChevronDown = wrap(Lucide.ChevronDown, 'slide-down');
export const ChevronLeft = wrap(Lucide.ChevronLeft, 'slide-left');
export const ChevronRight = wrap(Lucide.ChevronRight, 'slide-right');
export const Clock = wrap(Lucide.Clock, 'tick');
export const Download = wrap(Lucide.Download, 'slide-down');
export const Edit2 = wrap(Lucide.Edit2, 'wiggle');
export const ExternalLink = wrap(Lucide.ExternalLink, 'slide-right');
export const FileArchive = wrap(Lucide.FileArchive, 'squeeze');
export const Flame = wrap(Lucide.Flame, 'flicker');
export const Heart = wrap(Lucide.Heart, 'glow-pulse');
export const HelpCircle = wrap(Lucide.HelpCircle, 'pop-clean');
export const History = wrap(Lucide.History, 'spin-ccw');
export const ImageOff = wrap(Lucide.ImageOff, 'fade-flip');
export const ImagePlus = wrap(Lucide.ImagePlus, 'pop-clean');
export const Info = wrap(Lucide.Info, 'pop-clean');
export const LayoutGrid = wrap(Lucide.LayoutGrid, 'pop-clean');
export const List = wrap(Lucide.List, 'pop-clean');
export const Lock = wrap(Lucide.Lock, 'swing');
export const LockKeyhole = wrap(Lucide.LockKeyhole, 'swing');
export const LogIn = wrap(Lucide.LogIn, 'slide-right');
export const LogOut = wrap(Lucide.LogOut, 'slide-left');
export const Mail = wrap(Lucide.Mail, 'tilt');
export const Menu = wrap(Lucide.Menu, 'wiggle');
export const MessageSquare = wrap(Lucide.MessageSquare, 'pop-clean');
export const MoonStar = wrap(Lucide.MoonStar, 'glow-pulse');
export const MoveHorizontal = wrap(Lucide.MoveHorizontal, 'slide-right');
export const Package = wrap(Lucide.Package, 'corner-peek');
export const PenLine = wrap(Lucide.PenLine, 'wiggle');
export const Plus = wrap(Lucide.Plus, 'pop-clean');
export const RotateCcw = wrap(Lucide.RotateCcw, 'spin-ccw');
export const Scan = wrap(Lucide.Scan, 'ring-expand');
export const Search = wrap(Lucide.Search, 'blur-focus');
export const Settings = wrap(Lucide.Settings, 'spin-once');
export const Shield = wrap(Lucide.Shield, 'ring-expand');
export const SlidersHorizontal = wrap(Lucide.SlidersHorizontal, 'squeeze');
export const Sparkles = wrap(Lucide.Sparkles, 'glow-pulse');
export const Star = wrap(Lucide.Star, 'draw');
export const SunMedium = wrap(Lucide.SunMedium, 'glow-pulse');
export const Target = wrap(Lucide.Target, 'ring-expand');
export const Trash2 = wrap(Lucide.Trash2, 'wiggle');
export const Upload = wrap(Lucide.Upload, 'slide-up');
export const User = wrap(Lucide.User, 'pop-clean');
export const UserRound = wrap(Lucide.UserRound, 'pop-clean');
export const UserX = wrap(Lucide.UserX, 'shake');
export const Users = wrap(Lucide.Users, 'swing');
export const X = wrap(Lucide.X, 'fade-flip');
export const XCircle = wrap(Lucide.XCircle, 'fade-flip');
export const Zap = wrap(Lucide.Zap, 'flicker');
export const Award = wrap(Lucide.Award, 'ring-expand');
export const Trophy = wrap(Lucide.Trophy, 'tilt');
export const Medal = wrap(Lucide.Medal, 'swing');
export const Crown = wrap(Lucide.Crown, 'pop-clean');
export const Gem = wrap(Lucide.Gem, 'glow-pulse');
export const TrendingUp = wrap(Lucide.TrendingUp, 'slide-up');
export const CalendarCheck = wrap(Lucide.CalendarCheck, 'draw');
export const Percent = wrap(Lucide.Percent, 'pop-clean');
export const Bold = wrap(Lucide.Bold, 'pop-clean');
export const Italic = wrap(Lucide.Italic, 'tilt');
export const Underline = wrap(Lucide.Underline, 'slide-down');
export const Strikethrough = wrap(Lucide.Strikethrough, 'squeeze');
export const Link = wrap(Lucide.Link, 'swing');
export const AlignLeft = wrap(Lucide.AlignLeft, 'slide-left');
export const AlignCenter = wrap(Lucide.AlignCenter, 'pop-clean');
export const AlignRight = wrap(Lucide.AlignRight, 'slide-right');
export const MoreHorizontal = wrap(Lucide.MoreHorizontal, 'pop-clean');
export const ListOrdered = wrap(Lucide.ListOrdered, 'pop-clean');
export const Indent = wrap(Lucide.Indent, 'slide-right');
export const Outdent = wrap(Lucide.Outdent, 'slide-left');
export const Image = wrap(Lucide.Image, 'fade-flip');
export const Code = wrap(Lucide.Code, 'blur-focus');
export const Quote = wrap(Lucide.Quote, 'pop-clean');
export const Minus = wrap(Lucide.Minus, 'squeeze');
export const Code2 = wrap(Lucide.Code2, 'blur-focus');
export const Undo2 = wrap(Lucide.Undo2, 'spin-ccw');
export const Redo2 = wrap(Lucide.Redo2, 'spin-once');
export const Baseline = wrap(Lucide.Baseline, 'slide-down');
export const Highlighter = wrap(Lucide.Highlighter, 'tilt');
export const Palette = wrap(Lucide.Palette, 'glow-pulse');
export const Video = wrap(Lucide.Video, 'pop-clean');
export const Unlock = wrap(Lucide.Unlock, 'swing');
export const UploadCloud = wrap(Lucide.UploadCloud, 'slide-up');
export const Table = wrap(Lucide.Table, 'pop-clean');
export const Blocks = wrap(Lucide.Blocks, 'corner-peek');
export const ShieldCheck = wrap(Lucide.ShieldCheck, 'ring-expand');
